apiVersion: v1
kind: Service
metadata:
  name: cadvisor
  namespace: kube-system
spec:
  selector:
    app: cadvisor
  ports:
    - port: 8080
      targetPort: 8080
      name: http
      nodePort: 30080  # Expose on NodePort 30080
  type: NodePort
