# We dont need volumes for MySQL because data would just accumulate.

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672" # RabbitMQ protocol port
      - "15672:15672" # RabbitMQ management console
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - rabbitmq-net

  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: transactions_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    # We dont need volumes
    # volumes:
    #   - mysql_data:/var/lib/mysql
    networks:
      - mysql-net

  bank:
    build:
      context: ./bank
      dockerfile: Dockerfile
    image: pesekt1/bank:latest
    environment:
      PORT: 3002
      MESSAGE_SPEED: 1000
      API_URL: http://transaction-receiver:3000/transactions
    networks:
      - public-net

  transaction-receiver:
    build:
      context: ./transaction-receiver
      dockerfile: Dockerfile
    image: pesekt1/transaction-receiver:latest
    depends_on:
      - rabbitmq
    environment:
      PORT: 3000
      RABBITMQ_URL: amqp://rabbitmq
      QUEUE_NAME: transactionPayloads
    networks:
      - public-net
      - rabbitmq-net

  fraud-detection:
    build:
      context: ./fraud-detection
      dockerfile: Dockerfile
    image: pesekt1/fraud-detection:latest
    depends_on:
      - rabbitmq
    environment:
      PORT: 3003
      RABBITMQ_URL: amqp://rabbitmq
      INPUT_QUEUE_NAME: transactionPayloads
      ACCEPTED_QUEUE_NAME: acceptedTransactions
      SUSPICIOUS_QUEUE_NAME: suspiciousTransactions
    networks:
      - rabbitmq-net

  transaction-processing:
    build:
      context: ./transaction-processing
      dockerfile: Dockerfile
    image: pesekt1/transaction-processing:latest
    #removed the name because of scaling
    #container_name: transaction-processing
    depends_on:
      - rabbitmq
      - mysql
    #removed the port mapping because of scaling
    # ports:
    #   - "3001:3001"
    environment:
      PORT: 3001
      RABBITMQ_URL: amqp://rabbitmq
      QUEUE_NAME: acceptedTransactions
      DATABASE_URL: mysql://user:password@mysql:3306/transactions_db
      MESSAGE_PROCESSING_SPEED: 3000
    networks:
      - rabbitmq-net
      - mysql-net

# volumes:
#   mysql_data:

networks:
  public-net:
  rabbitmq-net:
  mysql-net:
