apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-adapter-config
  namespace: default
data:
  config.yaml: |
    rules:
    - seriesQuery: 'rabbitmq_queue_messages{queue="bankPackets"}'
      resources:
        overrides:
          namespace:
            resource: "namespace"
      name:
        matches: "^(.*)_sum$"
        as: "${1}"
      metricsQuery: 'avg(rabbitmq_queue_messages{queue="bankPackets"}) by (namespace)'