apiVersion: apps/v1
kind: Deployment
metadata:
  name: transaction-receiver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transaction-receiver
  template:
    metadata:
      labels:
        app: transaction-receiver
    spec:
      containers:
      - name: transaction-receiver
        image: pesekt1/transaction-receiver:latest
        ports:
        - containerPort: 3000
        env:
        - name: PORT
          value: "3000"
        - name: RABBITMQ_URL
          value: "amqp://rabbitmq"
        - name: QUEUE_NAME
          value: "transactionPayloads"
        - name: MESSAGE_SPEED
          value: "1000"
