apiVersion: v1
kind: Service
metadata:
  name: transaction-receiver
spec:
  selector:
    app: transaction-receiver
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 32000 # Expose the service on a NodePort
  type: NodePort