apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: 'rabbitmq'
        metrics_path: /metrics
        static_configs:
          - targets: ['rabbitmq-exporter:9419']
