apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-exporter
  namespace: default # Change this to match the namespace in your setup
spec:
  ports:
    - port: 9419
      targetPort: 9419
      protocol: TCP
  selector:
    app: rabbitmq-exporter
  type: ClusterIP
