apiVersion: apps/v1
kind: Deployment
metadata:
  name: transaction-processing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transaction-processing
  template:
    metadata:
      labels:
        app: transaction-processing
    spec:
      containers:
      - name: transaction-processing
        image: pesekt1/transaction-processing:latest
        imagePullPolicy: Always # Ensures the latest image is always pulled
        ports:
        - containerPort: 3001
        env:
        - name: PORT
          value: "3001"
        - name: RABBITMQ_URL
          value: "amqp://rabbitmq"
        - name: QUEUE_NAME
          value: "bankPackets"
        - name: DATABASE_URL
          value: "mysql://user:password@mysql:3306/bank_db"
        - name: MESSAGE_PROCESSING_SPEED
          value: "3000"