apiVersion: apps/v1
kind: Deployment
metadata:
  name: transaction-processing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transaction-processing
  template:
    metadata:
      labels:
        app: transaction-processing
    spec:
      containers:
      - name: transaction-processing
        image: pesekt1/transaction-processing:latest
        imagePullPolicy: Always # Ensures the latest image is always pulled
        ports:
        - containerPort: 3001
        env:
        - name: PORT
          value: "3001"
        - name: RABBITMQ_URL
          value: "amqp://rabbitmq"
        - name: QUEUE_NAME
          value: "acceptedTransactions"
        - name: DATABASE_URL
          value: "mysql://user:password@mysql:3306/transactions_db"
        - name: MESSAGE_PROCESSING_SPEED
          value: "3000"
        volumeMounts:
          - name: log-volume
            mountPath: /var/log/transaction-processing  # Mount the log directory to this path
      volumes:
        - name: log-volume
          hostPath:
            path: /var/log/transaction-processing  # This should be the location of logs on the node
            type: DirectoryOrCreate