name: Transaction receiver microservice - Build, Test, Push image to Docker Hub

on:
  push:
    branches:
      - main
    paths:
      - "transaction-receiver/**" # Trigger if files in transaction-receiver/ folder change

  workflow_dispatch: # Allows you to manually run the workflow from the Actions tab

jobs:
  integration-tests:
    runs-on: ubuntu-latest

    services:
      rabbitmq:
        image: rabbitmq:3-management
        ports:
          - 5672:5672
          - 15672:15672

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Install dependencies
        run: |
          cd transaction-receiver
          npm install

      - name: Run integration tests
        run: |
          cd transaction-receiver
          npx vitest run integration.test.ts

  system-tests:
    runs-on: ubuntu-latest

    services:
      rabbitmq:
        image: rabbitmq:3-management
        ports:
          - 5672:5672
          - 15672:15672

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Pull fraud-detection Docker image
        run: |
          docker pull pesekt1/fraud-detection:latest

          - name: Run fraud-detection service
          run: |
            docker run -d --name fraud-detection -p 3003:3003 --network host \
              -e PORT=3003 \
              -e RABBITMQ_URL=amqp://rabbitmq \
              -e INPUT_QUEUE_NAME=transactionPayloads \
              -e ACCEPTED_QUEUE_NAME=acceptedTransactions \
              -e SUSPICIOUS_QUEUE_NAME=suspiciousTransactions \
              pesekt1/fraud-detection:latest

      - name: Install dependencies
        run: |
          cd transaction-receiver
          npm install

      - name: Run system tests
        run: |
          cd transaction-receiver/tests
          npx vitest run system.test.ts

      - name: Capture fraud-detection logs
        if: failure()
        run: |
          echo "Capturing fraud-detection logs..."
          docker logs fraud-detection

  build-and-push:
    runs-on: ubuntu-latest
    needs: [integration-tests, system-tests]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }} # Store your Docker Hub username in GitHub Secrets
          password: ${{ secrets.DOCKER_PASSWORD }} # Store your Docker Hub password/token in GitHub Secrets

      - name: Build and push Docker image for transaction-receiver microservice
        run: |
          docker build -t pesekt1/transaction-receiver:latest ./transaction-receiver
          docker push pesekt1/transaction-receiver:latest
