name: Transaction receiver microservice - Build, Test, Push image to Docker Hub

on:
  push:
    branches:
      - main
    paths:
      - "transaction-receiver/**" # Trigger if files in transaction-receiver/ folder change

  workflow_dispatch: # Allows you to manually run the workflow from the Actions tab

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    services:
      rabbitmq:
        image: rabbitmq:3-management
        ports:
          - 5672:5672
          - 15672:15672
      fraud-detection:
        image: pesekt1/fraud-detection:latest
        ports:
          - 3003:3003
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Install dependencies
        run: |
          cd transaction-receiver
          npm install

      - name: Run integration tests
        run: |
          cd transaction-receiver
          npm test

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }} # Store your Docker Hub username in GitHub Secrets
          password: ${{ secrets.DOCKER_PASSWORD }} # Store your Docker Hub password/token in GitHub Secrets

      # Build and push Docker image for transaction-receiver microservice
      - name: Build and push Docker image for transaction-receiver microservice
        run: |
          docker build -t pesekt1/transaction-receiver:latest ./transaction-receiver
          docker push pesekt1/transaction-receiver:latest
