name: Deploy to Local Kubernetes

on:
  push:
    branches:
      - main
    paths:
      - "bank-microservice/**" # Trigger if files in bank-microservice/ folder change
      - "consumer-microservice/**" # Trigger if files in consumer-microservice/ folder change

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }} # Store your Docker Hub username in GitHub Secrets
          password: ${{ secrets.DOCKER_PASSWORD }} # Store your Docker Hub password/token in GitHub Secrets

      # Build and push for bank-microservice if changes are detected in bank-microservice directory
      - name: Build and push Docker image for bank-microservice
        if: contains(github.event.head_commit.message, 'bank-microservice/')
        run: |
          docker build -t pesekt1/bank-microservice:latest ./bank-microservice
          docker push pesekt1/bank-microservice:latest

      # Build and push for consumer-microservice if changes are detected in consumer-microservice directory
      - name: Build and push Docker image for consumer-microservice
        if: contains(github.event.head_commit.message, 'consumer-microservice/')
        run: |
          docker build -t pesekt1/consumer-microservice:latest ./consumer-microservice
          docker push pesekt1/consumer-microservice:latest
