name: Bank microservice - Build, test and push Docker image to Docker Hub

on:
  push:
    branches:
      - main
    paths:
      - "bank/**" # Trigger if files in bank/ folder change

  workflow_dispatch: # Allows you to manually run the workflow from the Actions tab

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install
        working-directory: ./bank

      - name: Set environment variables
        run: |
          echo "API_URL=http://transaction-receiver:3000/transactions" >> $GITHUB_ENV
          echo "MESSAGE_SPEED=1000" >> $GITHUB_ENV

      - name: Run unit tests
        run: npm test
        working-directory: ./bank

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }} # Store your Docker Hub username in GitHub Secrets
          password: ${{ secrets.DOCKER_PASSWORD }} # Store your Docker Hub password/token in GitHub Secrets

      # Build and push Docker image for bank microservice
      - name: Build and push Docker image for bank microservice
        run: |
          docker build -t pesekt1/bank:latest ./bank
          docker push pesekt1/bank:latest
